// This file is generated by PBX. You should never modify it.
namespace PBX
{
	public class MsgID
	{

		// chat.proto
		public const ushort sendMsg = 1001;
		public const ushort recvMsg = 1002;

		// login.proto
		public const ushort cgLogin = 2001;
		public const ushort gcLoginRet = 2002;
		public const ushort cgLogout = 2003;
		public const ushort gcLogoutRet = 2004;
		public const ushort cgEnterGame = 2005;
		public const ushort gcEnterGameRet = 2006;

		// scene.proto
		public const ushort gcEnterScene = 3001;
		public const ushort cgEnterSceneDone = 3002;
		public const ushort cgExitScene = 3003;
		public const ushort gcExitSceneRet = 3004;
		public const ushort gcOtherEnterScene = 3005;
		public const ushort gcNearbyPlayerInfo = 3006;
		public const ushort cgMoveTo = 3007;
		public const ushort gcMoveTo = 3008;

	}
}
