// This file is generated by PBX. You should never modify it.
namespace Protocol
{
	public enum MsgID
	{

		// chat.proto
		sendMsg = 1001,
		recvMsg = 1002,

		// login.proto
		csLogin = 2001,
		scLoginRet = 2002,
		csLogout = 2003,
		scLogoutRet = 2004,
		csEnterGame = 2005,
		scEnterGameRet = 2006,

		// scene.proto
		gcEnterScene = 3001,
		cgEnterSceneDone = 3002,
		cgExitScene = 3003,
		gcExitSceneRet = 3004,
		gcOtherEnterScene = 3005,
		gcNearbyPlayerInfo = 3006,
		cgMoveTo = 3007,
		gcMoveTo = 3008,

	}
}
