// This file is generated by PBX. You should never modify it.
namespace Protocol
{
	public enum MsgID
	{

		// chat.proto
		sendMsg = 1001,
		recvMsg = 1002,

		// login.proto
		csLogin = 2001,
		scLoginRet = 2002,
		csLogout = 2003,
		scLogoutRet = 2004,

		// scene.proto
		scMovementInfo = 3001,
		scPlayerInfo = 3002,
		scSceneInfo = 3003,
		scEnergyBallInfo = 3004,
		scBulletInfo = 3005,
		csJoin = 3006,
		scPlayerJoined = 3007,
		scPlayerQuit = 3008,
		csMoveTowards = 3009,
		scPlayerMove = 3010,
		csPing = 3011,
		scPing = 3012,
		csCollectEnergyBall = 3013,
		scCollectEnergyBall = 3014,
		scEnergyChange = 3015,
		csShoot = 3016,
		scShoot = 3017,
		scHitPlayer = 3018,

	}
}
